-- begin BLACKLIST_BLACK_LIST_ENTRY
alter table BLACKLIST_BLACK_LIST_ENTRY add constraint FK_BLACKLIST_BLACK_LIST_ENTRY_ON_ACCEPTOR foreign key (ACCEPTOR_ID) references BLACKLIST_ACCEPTOR_PROFILE(ID)^
alter table BLACKLIST_BLACK_LIST_ENTRY add constraint FK_BLACKLIST_BLACK_LIST_ENTRY_ON_VOTER foreign key (VOTER_ID) references BLACKLIST_VOTER_PROFILE(ID)^
create index IDX_BLACKLIST_BLACK_LIST_ENTRY_ON_ACCEPTOR on BLACKLIST_BLACK_LIST_ENTRY (ACCEPTOR_ID)^
create index IDX_BLACKLIST_BLACK_LIST_ENTRY_ON_VOTER on BLACKLIST_BLACK_LIST_ENTRY (VOTER_ID)^
-- end BLACKLIST_BLACK_LIST_ENTRY
-- begin BLACKLIST_REVIEWER_PROFILE
alter table BLACKLIST_REVIEWER_PROFILE add constraint FK_BLACKLIST_REVIEWER_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end BLACKLIST_REVIEWER_PROFILE
-- begin BLACKLIST_REVIEW
alter table BLACKLIST_REVIEW add constraint FK_BLACKLIST_REVIEW_ON_ENTRY foreign key (ENTRY_ID) references BLACKLIST_BLACK_LIST_ENTRY(ID)^
create index IDX_BLACKLIST_REVIEW_ON_ENTRY on BLACKLIST_REVIEW (ENTRY_ID)^
-- end BLACKLIST_REVIEW
-- begin BLACKLIST_ACCEPTOR_PROFILE
alter table BLACKLIST_ACCEPTOR_PROFILE add constraint FK_BLACKLIST_ACCEPTOR_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end BLACKLIST_ACCEPTOR_PROFILE
-- begin BLACKLIST_VOTER_PROFILE
alter table BLACKLIST_VOTER_PROFILE add constraint FK_BLACKLIST_VOTER_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end BLACKLIST_VOTER_PROFILE
-- begin BLACKLIST_BLACK_LIST_ENTRY_CONTACT_LINK
alter table BLACKLIST_BLACK_LIST_ENTRY_CONTACT_LINK add constraint FK_BLALISENTCON_ON_BLACK_LIST_ENTRY foreign key (BLACKLISTENTRY_ID) references BLACKLIST_BLACK_LIST_ENTRY(ID)^
alter table BLACKLIST_BLACK_LIST_ENTRY_CONTACT_LINK add constraint FK_BLALISENTCON_ON_CONTACT foreign key (CONTACT_ID) references BLACKLIST_CONTACT(ID)^
-- end BLACKLIST_BLACK_LIST_ENTRY_CONTACT_LINK
-- begin BLACKLIST_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK
alter table BLACKLIST_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_ACCPROBLALISENT_ON_ACCEPTOR_PROFILE foreign key (PROFILE_ID) references BLACKLIST_ACCEPTOR_PROFILE(ID)^
alter table BLACKLIST_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_ACCPROBLALISENT_ON_BLACK_LIST_ENTRY foreign key (ENTRY_ID) references BLACKLIST_BLACK_LIST_ENTRY(ID)^
-- end BLACKLIST_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK
-- begin BLACKLIST_VOTER_PROFILE_CONTACT_LINK
alter table BLACKLIST_VOTER_PROFILE_CONTACT_LINK add constraint FK_VOTPROCON_ON_VOTER_PROFILE foreign key (ROFILE_ID) references BLACKLIST_VOTER_PROFILE(ID)^
alter table BLACKLIST_VOTER_PROFILE_CONTACT_LINK add constraint FK_VOTPROCON_ON_CONTACT foreign key (CONTACT_ID) references BLACKLIST_CONTACT(ID)^
-- end BLACKLIST_VOTER_PROFILE_CONTACT_LINK
-- begin BLACKLIST_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK
alter table BLACKLIST_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_VOTPROBLALISENT_ON_VOTER_PROFILE foreign key (PROFILE_ID) references BLACKLIST_VOTER_PROFILE(ID)^
alter table BLACKLIST_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_VOTPROBLALISENT_ON_BLACK_LIST_ENTRY foreign key (ENTRY_ID) references BLACKLIST_BLACK_LIST_ENTRY(ID)^
-- end BLACKLIST_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK
-- begin BLACKLIST_BLACK_LIST_ENTRY_HISTORY_LINK
alter table BLACKLIST_BLACK_LIST_ENTRY_HISTORY_LINK add constraint FK_BLALISENTHIS_ON_BLACK_LIST_ENTRY foreign key (BLACKLISTENTRY_ID) references BLACKLIST_BLACK_LIST_ENTRY(ID)^
alter table BLACKLIST_BLACK_LIST_ENTRY_HISTORY_LINK add constraint FK_BLALISENTHIS_ON_HISTORY foreign key (HISTORY_ID) references BLACKLIST_HISTORY(ID)^
-- end BLACKLIST_BLACK_LIST_ENTRY_HISTORY_LINK
-- begin BLACKLIST_REVIEWER_PROFILE_REVIEW_LINK
alter table BLACKLIST_REVIEWER_PROFILE_REVIEW_LINK add constraint FK_REVPROREV_ON_REVIEWER_PROFILE foreign key (PROFILE_ID) references BLACKLIST_REVIEWER_PROFILE(ID)^
alter table BLACKLIST_REVIEWER_PROFILE_REVIEW_LINK add constraint FK_REVPROREV_ON_REVIEW foreign key (REVIEW_ID) references BLACKLIST_REVIEW(ID)^
-- end BLACKLIST_REVIEWER_PROFILE_REVIEW_LINK
-- begin BLACKLIST_BLACK_LIST_ENTRY_PLAYER_IP_LINK
alter table BLACKLIST_BLACK_LIST_ENTRY_PLAYER_IP_LINK add constraint FK_BLALISENTPLAIP_ON_BLACK_LIST_ENTRY foreign key (BLACKLISTENTRY_ID) references BLACKLIST_BLACK_LIST_ENTRY(ID)^
alter table BLACKLIST_BLACK_LIST_ENTRY_PLAYER_IP_LINK add constraint FK_BLALISENTPLAIP_ON_PLAYER_I_P foreign key (PLAYERIP_ID) references BLACKLIST_PLAYER_IP(ID)^
-- end BLACKLIST_BLACK_LIST_ENTRY_PLAYER_IP_LINK

-- begin BLACKLIST_REVIEWER_PROFILE_HISTORY_LINK
alter table BLACKLIST_REVIEWER_PROFILE_HISTORY_LINK add constraint FK_REVPROHIS_ON_REVIEWER_PROFILE foreign key (PROFILE_ID) references BLACKLIST_REVIEWER_PROFILE(ID)^
alter table BLACKLIST_REVIEWER_PROFILE_HISTORY_LINK add constraint FK_REVPROHIS_ON_HISTORY foreign key (HISTORY_ID) references BLACKLIST_HISTORY(ID)^
-- end BLACKLIST_REVIEWER_PROFILE_HISTORY_LINK
-- begin BLACKLIST_ACCEPTOR_PROFILE_CONTACT_LINK
alter table BLACKLIST_ACCEPTOR_PROFILE_CONTACT_LINK add constraint FK_ACCPROCON_ON_ACCEPTOR_PROFILE foreign key (PROFILE_ID) references BLACKLIST_ACCEPTOR_PROFILE(ID)^
alter table BLACKLIST_ACCEPTOR_PROFILE_CONTACT_LINK add constraint FK_ACCPROCON_ON_CONTACT foreign key (CONTACT_ID) references BLACKLIST_CONTACT(ID)^
-- end BLACKLIST_ACCEPTOR_PROFILE_CONTACT_LINK
-- begin BLACKLIST_REVIEWER_PROFILE_CONTACT_LINK
alter table BLACKLIST_REVIEWER_PROFILE_CONTACT_LINK add constraint FK_REVPROCON_ON_REVIEWER_PROFILE foreign key (PROFILE_ID) references BLACKLIST_REVIEWER_PROFILE(ID)^
alter table BLACKLIST_REVIEWER_PROFILE_CONTACT_LINK add constraint FK_REVPROCON_ON_CONTACT foreign key (CONTACT_ID) references BLACKLIST_CONTACT(ID)^
-- end BLACKLIST_REVIEWER_PROFILE_CONTACT_LINK
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_ACCEPTOR_PROFILE foreign key (ACCEPTOR_PROFILE_ID) references BLACKLIST_ACCEPTOR_PROFILE(ID)^
create index IDX_SEC_USER_ON_ACCEPTOR_PROFILE on SEC_USER (ACCEPTOR_PROFILE_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_REVIEWER_PROFILE foreign key (REVIEWER_PROFILE_ID) references BLACKLIST_REVIEWER_PROFILE(ID)^
create index IDX_SEC_USER_ON_REVIEWER_PROFILE on SEC_USER (REVIEWER_PROFILE_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_VOTER_PROFILE foreign key (VOTER_PROFILE_ID) references BLACKLIST_VOTER_PROFILE(ID)^
create index IDX_SEC_USER_ON_VOTER_PROFILE on SEC_USER (VOTER_PROFILE_ID)^
-- end SEC_USER
