alter table SEC_USER add constraint FK_SEC_USER_ON_REVIEWER_PROFILE foreign key (REVIEWER_PROFILE_ID) references BLACKLIST_REVIEWER_PROFILE(ID);
create index IDX_SEC_USER_ON_REVIEWER_PROFILE on SEC_USER (REVIEWER_PROFILE_ID);
