alter table SEC_USER add constraint FK_SEC_USER_ON_ACCEPTOR_PROFILE foreign key (ACCEPTOR_PROFILE_ID) references BLACKLIST_ACCEPTOR_PROFILE(ID);
create index IDX_SEC_USER_ON_ACCEPTOR_PROFILE on SEC_USER (ACCEPTOR_PROFILE_ID);
