-- begin BL_BLACK_LIST_ENTRY
alter table BL_BLACK_LIST_ENTRY add constraint FK_BL_BLACK_LIST_ENTRY_ON_ACCEPTOR foreign key (ACCEPTOR_ID) references BL_ACCEPTOR_PROFILE(ID)^
alter table BL_BLACK_LIST_ENTRY add constraint FK_BL_BLACK_LIST_ENTRY_ON_VOTER foreign key (VOTER_ID) references BL_VOTER_PROFILE(ID)^
create index IDX_BL_BLACK_LIST_ENTRY_ON_ACCEPTOR on BL_BLACK_LIST_ENTRY (ACCEPTOR_ID)^
create index IDX_BL_BLACK_LIST_ENTRY_ON_VOTER on BL_BLACK_LIST_ENTRY (VOTER_ID)^
-- end BL_BLACK_LIST_ENTRY
-- begin BL_REVIEWER_PROFILE
alter table BL_REVIEWER_PROFILE add constraint FK_BL_REVIEWER_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BL_REVIEWER_PROFILE_ON_USER on BL_REVIEWER_PROFILE (USER_ID)^
-- end BL_REVIEWER_PROFILE
-- begin BL_REVIEW
alter table BL_REVIEW add constraint FK_BL_REVIEW_ON_ENTRY foreign key (ENTRY_ID) references BL_BLACK_LIST_ENTRY(ID)^
alter table BL_REVIEW add constraint FK_BL_REVIEW_ON_PROFILE foreign key (PROFILE_ID) references BL_REVIEWER_PROFILE(ID)^
create index IDX_BL_REVIEW_ON_ENTRY on BL_REVIEW (ENTRY_ID)^
create index IDX_BL_REVIEW_ON_PROFILE on BL_REVIEW (PROFILE_ID)^
-- end BL_REVIEW
-- begin BL_ACCEPTOR_PROFILE
alter table BL_ACCEPTOR_PROFILE add constraint FK_BL_ACCEPTOR_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BL_ACCEPTOR_PROFILE_ON_USER on BL_ACCEPTOR_PROFILE (USER_ID)^
-- end BL_ACCEPTOR_PROFILE
-- begin BL_VOTER_PROFILE
alter table BL_VOTER_PROFILE add constraint FK_BL_VOTER_PROFILE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BL_VOTER_PROFILE_ON_USER on BL_VOTER_PROFILE (USER_ID)^
-- end BL_VOTER_PROFILE
-- begin BL_BLACK_LIST_ENTRY_HISTORY_LINK
alter table BL_BLACK_LIST_ENTRY_HISTORY_LINK add constraint FK_BLALISENTHIS_ON_BLACK_LIST_ENTRY foreign key (BLACKLISTENTRY_ID) references BL_BLACK_LIST_ENTRY(ID)^
alter table BL_BLACK_LIST_ENTRY_HISTORY_LINK add constraint FK_BLALISENTHIS_ON_HISTORY foreign key (HISTORY_ID) references BL_HISTORY(ID)^
-- end BL_BLACK_LIST_ENTRY_HISTORY_LINK
-- begin BL_REVIEWER_PROFILE_HISTORY_LINK
alter table BL_REVIEWER_PROFILE_HISTORY_LINK add constraint FK_REVPROHIS_ON_REVIEWER_PROFILE foreign key (PROFILE_ID) references BL_REVIEWER_PROFILE(ID)^
alter table BL_REVIEWER_PROFILE_HISTORY_LINK add constraint FK_REVPROHIS_ON_HISTORY foreign key (HISTORY_ID) references BL_HISTORY(ID)^
-- end BL_REVIEWER_PROFILE_HISTORY_LINK
-- begin BL_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK
alter table BL_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_ACCPROBLALISENT_ON_ACCEPTOR_PROFILE foreign key (PROFILE_ID) references BL_ACCEPTOR_PROFILE(ID)^
alter table BL_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_ACCPROBLALISENT_ON_BLACK_LIST_ENTRY foreign key (ENTRY_ID) references BL_BLACK_LIST_ENTRY(ID)^
-- end BL_ACCEPTOR_PROFILE_BLACK_LIST_ENTRY_LINK
-- begin BL_REVIEWER_PROFILE_CONTACT_LINK
alter table BL_REVIEWER_PROFILE_CONTACT_LINK add constraint FK_REVPROCON_ON_REVIEWER_PROFILE foreign key (PROFILE_ID) references BL_REVIEWER_PROFILE(ID)^
alter table BL_REVIEWER_PROFILE_CONTACT_LINK add constraint FK_REVPROCON_ON_CONTACT foreign key (CONTACT_ID) references BL_CONTACT(ID)^
-- end BL_REVIEWER_PROFILE_CONTACT_LINK
-- begin BL_REVIEWER_PROFILE_REVIEW_LINK
alter table BL_REVIEWER_PROFILE_REVIEW_LINK add constraint FK_REVPROREV_ON_REVIEWER_PROFILE foreign key (PROFILE_ID) references BL_REVIEWER_PROFILE(ID)^
alter table BL_REVIEWER_PROFILE_REVIEW_LINK add constraint FK_REVPROREV_ON_REVIEW foreign key (REVIEW_ID) references BL_REVIEW(ID)^
-- end BL_REVIEWER_PROFILE_REVIEW_LINK
-- begin BL_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK
alter table BL_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_VOTPROBLALISENT_ON_VOTER_PROFILE foreign key (PROFILE_ID) references BL_VOTER_PROFILE(ID)^
alter table BL_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK add constraint FK_VOTPROBLALISENT_ON_BLACK_LIST_ENTRY foreign key (ENTRY_ID) references BL_BLACK_LIST_ENTRY(ID)^
-- end BL_VOTER_PROFILE_BLACK_LIST_ENTRY_LINK
-- begin BL_BLACK_LIST_ENTRY_PLAYER_IP_LINK
alter table BL_BLACK_LIST_ENTRY_PLAYER_IP_LINK add constraint FK_BLALISENTPLAIP_ON_BLACK_LIST_ENTRY foreign key (BLACKLISTENTRY_ID) references BL_BLACK_LIST_ENTRY(ID)^
alter table BL_BLACK_LIST_ENTRY_PLAYER_IP_LINK add constraint FK_BLALISENTPLAIP_ON_PLAYER_I_P foreign key (PLAYERIP_ID) references BL_PLAYER_IP(ID)^
-- end BL_BLACK_LIST_ENTRY_PLAYER_IP_LINK
-- begin BL_ACCEPTOR_PROFILE_CONTACT_LINK
alter table BL_ACCEPTOR_PROFILE_CONTACT_LINK add constraint FK_ACCPROCON_ON_ACCEPTOR_PROFILE foreign key (PROFILE_ID) references BL_ACCEPTOR_PROFILE(ID)^
alter table BL_ACCEPTOR_PROFILE_CONTACT_LINK add constraint FK_ACCPROCON_ON_CONTACT foreign key (CONTACT_ID) references BL_CONTACT(ID)^
-- end BL_ACCEPTOR_PROFILE_CONTACT_LINK
-- begin BL_VOTER_PROFILE_CONTACT_LINK
alter table BL_VOTER_PROFILE_CONTACT_LINK add constraint FK_VOTPROCON_ON_VOTER_PROFILE foreign key (ROFILE_ID) references BL_VOTER_PROFILE(ID)^
alter table BL_VOTER_PROFILE_CONTACT_LINK add constraint FK_VOTPROCON_ON_CONTACT foreign key (CONTACT_ID) references BL_CONTACT(ID)^
-- end BL_VOTER_PROFILE_CONTACT_LINK
-- begin BL_BLACK_LIST_ENTRY_CONTACT_LINK
alter table BL_BLACK_LIST_ENTRY_CONTACT_LINK add constraint FK_BLALISENTCON_ON_BLACK_LIST_ENTRY foreign key (BLACKLISTENTRY_ID) references BL_BLACK_LIST_ENTRY(ID)^
alter table BL_BLACK_LIST_ENTRY_CONTACT_LINK add constraint FK_BLALISENTCON_ON_CONTACT foreign key (CONTACT_ID) references BL_CONTACT(ID)^
-- end BL_BLACK_LIST_ENTRY_CONTACT_LINK
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_ACCEPTOR_PROFILE foreign key (ACCEPTOR_PROFILE_ID) references BL_ACCEPTOR_PROFILE(ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_REVIEWER_PROFILE foreign key (REVIEWER_PROFILE_ID) references BL_REVIEWER_PROFILE(ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_VOTER_PROFILE foreign key (VOTER_PROFILE_ID) references BL_VOTER_PROFILE(ID)^
-- end SEC_USER
