alter table BL_EXPORT_PARAM add constraint FK_BL_EXPORT_PARAM_ON_CONSUMER foreign key (CONSUMER_ID) references BL_EXPORT_CONSUMER(ID);
create index IDX_BL_EXPORT_PARAM_ON_CONSUMER on BL_EXPORT_PARAM (CONSUMER_ID);
